// Code generated by goctl. DO NOT EDIT!
// Source: follow_service.proto

package server

import (
	"context"
	"encoding/json"

	"follow_system/follow_service/internal/logic"
	"follow_system/follow_service/internal/svc"
	"follow_system/follow_service/root/go/src/follow_system/pb/follow_service"
	"github.com/zeromicro/go-zero/core/logx"
	"google.golang.org/grpc/metadata"
)

type FollowServiceServer struct {
	svcCtx *svc.ServiceContext
	follow_service.UnimplementedFollowServiceServer
}

func NewFollowServiceServer(svcCtx *svc.ServiceContext) *FollowServiceServer {
	return &FollowServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowServiceServer) Ping(ctx context.Context, in *follow_service.FollowReq) (*follow_service.FollowRsp, error) {
	tokenCtx := svc.TokenContext{
		Context: ctx,
	}
	md, ok := metadata.FromIncomingContext(ctx)
	if ok {
		if datas, ok := md["context"]; ok && len(datas) > 0 {
			if err := json.Unmarshal([]byte(datas[0]), &tokenCtx.COMM); err != nil {
				logx.WithContext(ctx).Error("context common data json Unmarshal failed, data:", datas[0], "err:", err)
			}

		}
	}
	l := logic.NewPingLogic(tokenCtx, s.svcCtx)
	return l.Ping(in)
}
