// Code generated by goctl. DO NOT EDIT!
// Source: Follow.proto

package followservice

import (
	"context"

	"follow_system/pb/Follow"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FollowRQ        = Follow.FollowRQ
	FollowRS        = Follow.FollowRS
	GetFansListRQ   = Follow.GetFansListRQ
	GetFansListRS   = Follow.GetFansListRS
	GetFollowListRQ = Follow.GetFollowListRQ
	GetFollowListRS = Follow.GetFollowListRS

	FollowService interface {
		Follow(ctx context.Context, in *FollowRQ, opts ...grpc.CallOption) (*FollowRS, error)
		GetFollowList(ctx context.Context, in *GetFollowListRQ, opts ...grpc.CallOption) (*GetFollowListRS, error)
		GetFansList(ctx context.Context, in *GetFansListRQ, opts ...grpc.CallOption) (*GetFansListRS, error)
	}

	defaultFollowService struct {
		cli zrpc.Client
	}
)

func NewFollowService(cli zrpc.Client) FollowService {
	return &defaultFollowService{
		cli: cli,
	}
}

func (m *defaultFollowService) Follow(ctx context.Context, in *FollowRQ, opts ...grpc.CallOption) (*FollowRS, error) {
	client := Follow.NewFollowServiceClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

func (m *defaultFollowService) GetFollowList(ctx context.Context, in *GetFollowListRQ, opts ...grpc.CallOption) (*GetFollowListRS, error) {
	client := Follow.NewFollowServiceClient(m.cli.Conn())
	return client.GetFollowList(ctx, in, opts...)
}

func (m *defaultFollowService) GetFansList(ctx context.Context, in *GetFansListRQ, opts ...grpc.CallOption) (*GetFansListRS, error) {
	client := Follow.NewFollowServiceClient(m.cli.Conn())
	return client.GetFansList(ctx, in, opts...)
}
