// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.14.0
// source: follow_service.proto

package follow_service

import (
	follow_system "./follow_system"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opt       int32 `protobuf:"varint,1,opt,name=opt,proto3" json:"opt,omitempty"` // 0-关注 1-取消
	Uid       int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Fans      int64 `protobuf:"varint,3,opt,name=fans,proto3" json:"fans,omitempty"`
	EventType int32 `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
}

func (x *FollowRQ) Reset() {
	*x = FollowRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRQ) ProtoMessage() {}

func (x *FollowRQ) ProtoReflect() protoreflect.Message {
	mi := &file_follow_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRQ.ProtoReflect.Descriptor instead.
func (*FollowRQ) Descriptor() ([]byte, []int) {
	return file_follow_service_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRQ) GetOpt() int32 {
	if x != nil {
		return x.Opt
	}
	return 0
}

func (x *FollowRQ) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FollowRQ) GetFans() int64 {
	if x != nil {
		return x.Fans
	}
	return 0
}

func (x *FollowRQ) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

type FollowRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err       *follow_system.ErrorInfo `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Opt       int32                    `protobuf:"varint,2,opt,name=opt,proto3" json:"opt,omitempty"`
	Uid       int64                    `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Fans      int64                    `protobuf:"varint,4,opt,name=fans,proto3" json:"fans,omitempty"`
	EventType int32                    `protobuf:"varint,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
}

func (x *FollowRS) Reset() {
	*x = FollowRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRS) ProtoMessage() {}

func (x *FollowRS) ProtoReflect() protoreflect.Message {
	mi := &file_follow_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRS.ProtoReflect.Descriptor instead.
func (*FollowRS) Descriptor() ([]byte, []int) {
	return file_follow_service_proto_rawDescGZIP(), []int{1}
}

func (x *FollowRS) GetErr() *follow_system.ErrorInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *FollowRS) GetOpt() int32 {
	if x != nil {
		return x.Opt
	}
	return 0
}

func (x *FollowRS) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FollowRS) GetFans() int64 {
	if x != nil {
		return x.Fans
	}
	return 0
}

func (x *FollowRS) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

type GetFollowListRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType int32 `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Uid       int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetFollowListRQ) Reset() {
	*x = GetFollowListRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFollowListRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowListRQ) ProtoMessage() {}

func (x *GetFollowListRQ) ProtoReflect() protoreflect.Message {
	mi := &file_follow_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowListRQ.ProtoReflect.Descriptor instead.
func (*GetFollowListRQ) Descriptor() ([]byte, []int) {
	return file_follow_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowListRQ) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *GetFollowListRQ) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetFollowListRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType  int32                    `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Uid        int64                    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	FollowList []int64                  `protobuf:"varint,3,rep,packed,name=follow_list,json=followList,proto3" json:"follow_list,omitempty"`
	Err        *follow_system.ErrorInfo `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *GetFollowListRS) Reset() {
	*x = GetFollowListRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFollowListRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowListRS) ProtoMessage() {}

func (x *GetFollowListRS) ProtoReflect() protoreflect.Message {
	mi := &file_follow_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowListRS.ProtoReflect.Descriptor instead.
func (*GetFollowListRS) Descriptor() ([]byte, []int) {
	return file_follow_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetFollowListRS) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *GetFollowListRS) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetFollowListRS) GetFollowList() []int64 {
	if x != nil {
		return x.FollowList
	}
	return nil
}

func (x *GetFollowListRS) GetErr() *follow_system.ErrorInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

type GetFansListRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType int32 `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Uid       int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetFansListRQ) Reset() {
	*x = GetFansListRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFansListRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFansListRQ) ProtoMessage() {}

func (x *GetFansListRQ) ProtoReflect() protoreflect.Message {
	mi := &file_follow_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFansListRQ.ProtoReflect.Descriptor instead.
func (*GetFansListRQ) Descriptor() ([]byte, []int) {
	return file_follow_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetFansListRQ) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *GetFansListRQ) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetFansListRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType int32                    `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Uid       int64                    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	FansList  []int64                  `protobuf:"varint,3,rep,packed,name=fans_list,json=fansList,proto3" json:"fans_list,omitempty"`
	Err       *follow_system.ErrorInfo `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *GetFansListRS) Reset() {
	*x = GetFansListRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_follow_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFansListRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFansListRS) ProtoMessage() {}

func (x *GetFansListRS) ProtoReflect() protoreflect.Message {
	mi := &file_follow_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFansListRS.ProtoReflect.Descriptor instead.
func (*GetFansListRS) Descriptor() ([]byte, []int) {
	return file_follow_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetFansListRS) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *GetFansListRS) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetFansListRS) GetFansList() []int64 {
	if x != nil {
		return x.FansList
	}
	return nil
}

func (x *GetFansListRS) GetErr() *follow_system.ErrorInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

var File_follow_service_proto protoreflect.FileDescriptor

var file_follow_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x61, 0x0a, 0x08, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x51,
	0x12, 0x10, 0x0a, 0x03, 0x6f, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6f,
	0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x61, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x66, 0x61, 0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x08, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x52, 0x53, 0x12, 0x23, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x70, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6f, 0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x61, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x61, 0x6e,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x42, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x51, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x53, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x03, 0x65, 0x72,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22,
	0x40, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x51,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x22, 0x82, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6e, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x53, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x61, 0x6e, 0x73, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x66, 0x61, 0x6e, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32, 0xee, 0x01, 0x0a, 0x0e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x12, 0x18, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x51, 0x1a, 0x18, 0x2e,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x53, 0x12, 0x51, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x51, 0x1a, 0x1f, 0x2e, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x53, 0x12, 0x4b, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x46, 0x61, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61,
	0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x51, 0x1a, 0x1d, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6e,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x53, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_follow_service_proto_rawDescOnce sync.Once
	file_follow_service_proto_rawDescData = file_follow_service_proto_rawDesc
)

func file_follow_service_proto_rawDescGZIP() []byte {
	file_follow_service_proto_rawDescOnce.Do(func() {
		file_follow_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_follow_service_proto_rawDescData)
	})
	return file_follow_service_proto_rawDescData
}

var file_follow_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_follow_service_proto_goTypes = []interface{}{
	(*FollowRQ)(nil),                // 0: follow_service.FollowRQ
	(*FollowRS)(nil),                // 1: follow_service.FollowRS
	(*GetFollowListRQ)(nil),         // 2: follow_service.GetFollowListRQ
	(*GetFollowListRS)(nil),         // 3: follow_service.GetFollowListRS
	(*GetFansListRQ)(nil),           // 4: follow_service.GetFansListRQ
	(*GetFansListRS)(nil),           // 5: follow_service.GetFansListRS
	(*follow_system.ErrorInfo)(nil), // 6: common.ErrorInfo
}
var file_follow_service_proto_depIdxs = []int32{
	6, // 0: follow_service.FollowRS.err:type_name -> common.ErrorInfo
	6, // 1: follow_service.GetFollowListRS.err:type_name -> common.ErrorInfo
	6, // 2: follow_service.GetFansListRS.err:type_name -> common.ErrorInfo
	0, // 3: follow_service.Follow_service.Follow:input_type -> follow_service.FollowRQ
	2, // 4: follow_service.Follow_service.GetFollowList:input_type -> follow_service.GetFollowListRQ
	4, // 5: follow_service.Follow_service.GetFansList:input_type -> follow_service.GetFansListRQ
	1, // 6: follow_service.Follow_service.Follow:output_type -> follow_service.FollowRS
	3, // 7: follow_service.Follow_service.GetFollowList:output_type -> follow_service.GetFollowListRS
	5, // 8: follow_service.Follow_service.GetFansList:output_type -> follow_service.GetFansListRS
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_follow_service_proto_init() }
func file_follow_service_proto_init() {
	if File_follow_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_follow_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFollowListRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFollowListRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFansListRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_follow_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFansListRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_follow_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_follow_service_proto_goTypes,
		DependencyIndexes: file_follow_service_proto_depIdxs,
		MessageInfos:      file_follow_service_proto_msgTypes,
	}.Build()
	File_follow_service_proto = out.File
	file_follow_service_proto_rawDesc = nil
	file_follow_service_proto_goTypes = nil
	file_follow_service_proto_depIdxs = nil
}
